#!/usr/bin/env node

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import YAML from "yaml";

const skillRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = path.join(skillRoot, "schemas", "troubleshoot-result.schema.yaml");
const outputPath = path.join(skillRoot, "references", "generated", "troubleshoot-contract.md");

function resolveRef(schema, ref) {
  if (!ref.startsWith("#/")) throw new Error(`unsupported schema reference: ${ref}`);
  return ref.slice(2).split("/").reduce((node, token) => node[token], schema);
}

function resolveNode(schema, node) {
  return node && node.$ref ? resolveNode(schema, resolveRef(schema, node.$ref)) : node;
}

function nodeType(schema, node) {
  const resolved = resolveNode(schema, node);
  if (resolved.type) return resolved.type;
  if (resolved.enum) return "enum";
  if (resolved.anyOf) {
    return resolved.anyOf.map((option) => nodeType(schema, option)).join(" | ");
  }
  return "schema";
}

function collectRequired(schema, node, prefix = "") {
  const resolved = resolveNode(schema, node);
  const lines = [];
  for (const name of resolved.required || []) {
    const child = resolved.properties?.[name];
    if (!child) throw new Error(`required property lacks schema: ${prefix}${name}`);
    const childPath = prefix ? `${prefix}.${name}` : name;
    lines.push(`- \`${childPath}\` — ${nodeType(schema, child)}`);
    const childResolved = resolveNode(schema, child);
    if (childResolved.type === "object" && childResolved.required) {
      lines.push(...collectRequired(schema, childResolved, childPath));
    }
  }
  return lines;
}

function collectEnumValues(schema, node) {
  const resolved = resolveNode(schema, node);
  const values = [];
  if (resolved.enum) values.push(...resolved.enum);
  for (const option of resolved.anyOf || []) values.push(...collectEnumValues(schema, option));
  return values;
}

function render(schemaText) {
  const schema = YAML.parse(schemaText);
  const digest = crypto.createHash("sha256").update(schemaText).digest("hex");
  const lines = [
    "<!-- generated by scripts/generate_troubleshoot_contract.mjs; do not edit -->",
    `<!-- schema_sha256: ${digest} -->`,
    "# TroubleshootResult contract",
    "",
    "This compact reference is generated from `schemas/troubleshoot-result.schema.yaml`. The YAML schema remains authoritative.",
    "",
    "## Required paths",
    "",
    ...collectRequired(schema, schema),
    "",
    "## Canonical enums",
    "",
  ];

  for (const [name, definition] of Object.entries(schema.$defs || {})) {
    const values = collectEnumValues(schema, definition);
    if (!values.length) continue;
    lines.push(`### ${name}`, "", values.map((value) => `- \`${String(value)}\``).join("\n"), "");
  }
  const nextHandoff = collectEnumValues(
    schema,
    schema.properties.TroubleshootResult.properties.next_handoff,
  );
  lines.push("### next_handoff", "", ...nextHandoff.map((value) => `- \`${value}\``), "");
  return `${lines.join("\n").trimEnd()}\n`;
}

const schemaText = fs.readFileSync(schemaPath, "utf8");
const expected = render(schemaText);
const check = process.argv.slice(2).includes("--check");
if (check) {
  const actual = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8") : "";
  if (actual !== expected) {
    process.stderr.write("generated troubleshoot contract is stale\n");
    process.exit(1);
  }
} else {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, expected);
}
